### ISSUE TITLE
Migrate away from TSDX

### ISSUE THREAD

**Issue by hoeck** [hoeck/simple-runtypes#63]
As [TSDX](https://www.npmjs.com/package/tsdx) seems rather [unmaintained and its future unclear](https://github.com/jaredpalmer/tsdx/issues/1065).

Replace it preferably with something that takes care with packaging and supports the same features as TSDX (minifying, sourcemaps, dts files, esm, cjs).

[TSUP](https://github.com/egoist/tsup) looks like a good candidate (shoutout to @remnantkevin for the suggestion).

**Comment by remnantkevin** [comment]
Once the `nonStrict` modifier work has been finished (whether or not it "lands" is a different question), I would like to give this a look, if that's okay. I've been working with `esbuild` at work, and have used `tsup` on small personal projects. From my research, `tsup` seems to still be a good option as a replacement for `tsdx`, and it is still being actively developed and maintained. In my very limited experience, `tsup` seems to also be a better option than `vite` for the `simple-runtypes` use case: while `vite` can do more and has a substantial community of plugins, etc., most of that is not relevant for `simple-runtypes`, as far as I understand. `tsup` does more (of what is needed in this use case) with less configuration and simpler options. I can do more of a direct comparison between `tsdx` and `tsup` (for the `simple-runtypes` use case) once I've had a chance to play around with it locally with `simple-runtypes`.

As part of moving to `tsup`, the configuration options that are used can also addresses another, related, issue (#86).

**Comment by hoeck** [comment]
@remnantkevin thanks for looking into this (BTW glad seeing you're still here).

Sounds like tsup is what I have been looking for. It also seems to support both, [cjs and esm](https://antfu.me/posts/publish-esm-and-cjs).
