### ISSUE TITLE
nonStrict modifier

### ISSUE THREAD

**Issue by hoeck** [hoeck/simple-runtypes#68]
Change the existing `sloppyRecord` runtype functionality into a `nonStrict` combinator that works on `record` runtypes, similar to how `pick` works atm.

Before:

```
import * as st from 'simple-runtypes'

const item = st.sloppyRecord({
  id: st.number(),
  label: st.string(),
})
```

After:

```
import * as st from 'simple-runtypes'

const item = st.nonStrict(
    st.record({
        id: st.number(),
        label: st.string(),
    }),
)
```

Reasons:

* "sloppy" has a bad connotation that looks weird when spread out all over runtype definitions
* using a modifier function allows for separating the record definition from the way its parsed
* it is still possible to mix nonStrict with strict objects in a single runtype

**Comment by arv** [comment]
Should `nonStrict`  recurse into sub records?

**Comment by hoeck** [comment]
I don't think it should recurse into sub records.

Whenever I am using "sloppy", it is always at the top level of API requests/responses to ignore meta fields such as _requestTimestamp or _createdAt.

**Comment by seanaguinaga** [comment]
Typescript defs for this appear to not be updated

![image](https://github.com/hoeck/simple-runtypes/assets/15254340/f98bde06-2bc6-4de3-a62c-c1784cef4b98)

![image](https://github.com/hoeck/simple-runtypes/assets/15254340/7023e770-da6c-42cb-9027-9e2568d141ff)

**Comment by hoeck** [comment]
sorry @seanaguinaga I still have to release this and there are some bugs waiting to be fixed too.

**Comment by seanaguinaga** [comment]
Got it! nbd! :)
